language: python

python:
  - 3.5.0

services:
  - postgresql

env:
  - DJANGO=1.9.1

before_install:
  - export DJANGO_SETTINGS_MODULE=upgraid.travis-settings
  - export PYTHONPATH=$HOME/builds/UpgrAID/UpgrAID
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE upgraid;" -U postgres
  - python manage.py syncdb

script:
 - coverage run --source='.' manage.py test post user

after_success:
 - coveralls