# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='event',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
