# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20151209_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Goal')),
            ],
        ),
    ]
