# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20151210_1914'),
        ('post', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Theme'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
