# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20151214_2038'),
        ('post', '0007_auto_20151214_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
            preserve_default=False,
        ),
    ]
