# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20151218_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='group',
            field=models.ForeignKey(blank=True, default=50, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
            preserve_default=False,
        ),
    ]
