# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20160101_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set([('comment', 'user')]),
        ),
    ]
