# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20151207_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 9, 17, 30, 32, 155482, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
