# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20151209_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
