# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20151210_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Rank'),
        ),
    ]
