# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20151214_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='required_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
