# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20151214_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('Goal', 'Goal'), ('Post', 'Post'), ('Earned', 'Earned')], default='Goal', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='point',
            field=models.IntegerField(default=2),
        ),
    ]
