# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20151216_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.NullBooleanField(),
        ),
    ]
