# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_friendship_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
