# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20151217_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='user.Rank'),
        ),
    ]
