# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20160101_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgegift',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
