# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20160103_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
    ]
